CREATE TABLE random_recipe_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    email TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    p_word TEXT NOT NULL
);